inputFile = open('input.txt', 'r', encoding='utf8')
outputFile = open('output.txt', 'w', encoding='utf8')
n, m = map(int, inputFile.readline().split())
data = list(map(int, inputFile.readlines()))
a = set(data[:n])
b = set(data[n:])
AintB = a & b
l = len(AintB)
print(l, file=outputFile)
print(*sorted(AintB), file=outputFile)
otherA = sorted(a - AintB)
otherB = sorted(b - AintB)
print(n - l, file=outputFile)
print(*otherA, file=outputFile)
print(m - l, file=outputFile)
print(*otherB, file=outputFile)
inputFile.close()
outputFile.close()
